#ifndef __OPTIMIZATIONS_H__
#define __OPTIMIZATIONS_H__
#include "configure.h"

#ifdef OBVIOUS_OPTIMIZATIONS
#define OPTIMIZE_IF_CONSTANT_CONDITION
#define OPTIMIZE_WHILE_CONSTANT_CONDITION
#define OPTIMIZE_FOR_CONSTANT_CONDITION
#define OPTIMIZE_DO_WHILE_CONSTANT_CONDITION
#define OPTIMIZE_DONT_ADD_ZERO
#endif

#endif
